### ISSUE TITLE
How to have it to rate things from the universal Plex database?

### ISSUE THREAD

**Issue by balupton** [haec0007/plex-imdb-ratings#7]
Plex in 2024 allows one to rate, mark as watched, and watchlist items that aren't in your plex library. Currently this tool only supports rating items that are inside our plex library. Is supporting this universal library possible? As most of the items I've rated on IMDB aren't actually in my plex library.

**Comment by haec0007** [comment]
This might be doable. I'll have to take a look at the Plex API to see if rating items outside the user's library is supported.

**Comment by haec0007** [comment]
According to this outstanding issue in the python-plexapi repository, it doesn't appear to be possible to rate non-library items from the API at this time.

https://github.com/pkkid/python-plexapi/issues/1137
